social/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^train_auto/$', views.train_auto, name='train_auto'),
    url(r'^station_auto/$', views.station_auto, name='station_auto'),
    url(r'^live_status/$', views.live_status, name='live_status'),
    url(r'^pnr_status/$', views.pnr_status, name='pnr_status'),
    url(r'^train_route/$', views.train_route, name='train_route'),
    url(r'^seat_availability/$', views.seat_availability, name='seat_availability'),
    url(r'^train_bw_station/$', views.train_bw_station, name='train_bw_station'),
    url(r'^fare_enquiry/$', views.fare_enquiry, name='fare_enquiry'),
    url(r'^live_station/$', views.live_station, name='live_station'),
    url(r'^cancelled_train/$', views.cancelled_train, name='cancelled_train'),
    url(r'^rescheduled_train/$', views.rescheduled_train, name='rescheduled_train'),
]

social_network/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^trainapp/', include('social.urls', namespace='social'))
]

social/models.py
from django.db import models

class User(models.Model):
    username = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.username

social/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(label='username', max_length=200)
    email = forms.CharField(max_length=200)
    password = forms.CharField(label='password', max_length=200)

class LoginForm(forms.Form):
    username = forms.CharField(label='username', max_length=200)
    password = forms.CharField(label='password', max_length=200)
    keep_logged_in = forms.CharField(label='keep_logged_in')

class trainStatus(forms.Form):
    train_number = forms.CharField(max_length=10)
    date = forms.CharField(max_length=10)

class pnrStatus(forms.Form):
    pnr_number = forms.CharField(max_length=20)

class seatAvailability(forms.Form):
    train_number = forms.CharField(max_length=10)
    source_code = forms.CharField(max_length=10)
    dest_code = forms.CharField(max_length=10)
    class_code = forms.CharField(max_length=10)
    quota_code = forms.CharField(max_length=10)
    date = forms.CharField(max_length=10)

class trainBWstation(forms.Form):
    source_code = forms.CharField(max_length=10)
    dest_code = forms.CharField(max_length=10)
    date = forms.CharField(max_length=10)

class fareEnquiry(forms.Form):
    train_number = forms.CharField(max_length=10)
    source_code = forms.CharField(max_length=10)
    dest_code = forms.CharField(max_length=10)
    quota_code = forms.CharField(max_length=10)
    age = forms.CharField(max_length=3)
    date = forms.CharField(max_length=10)

class liveStation(forms.Form):
    station_code = forms.CharField(max_length=10)
    hours = forms.CharField(max_length=1)

class cancelledTrain(forms.Form):
    date = forms.CharField(max_length=10)

class rescheduledTrain(forms.Form):
    date = forms.CharField(max_length=10)

class Info(forms.Form):
    info = forms.CharField(max_length=10)

social/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import User
from .forms import LoginForm, RegisterForm, trainStatus, pnrStatus, seatAvailability,trainBWstation, fareEnquiry, liveStation, Info, cancelledTrain, rescheduledTrain
import datetime
import requests
import json
from urllib.request import urlopen

def index(request):
    return render(request, 'trainapp/live_status.html')

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            if username is None:
                error_msg = "Please enter the username"
                return render(request, 'social/register.html', {'error_msg':error_msg, 'form':form})
            elif User.objects.filter(username=username).exists():
                error_msg = "Username already exists"
                return render(request, 'social/register.html', {'error_msg': error_msg, 'form': form})
            elif User.objects.filter(email=email).exists():
                error_msg = "You are already registered user"
                return render(request, 'social/register.html', {'error_msg': error_msg, 'form': form})
            else:
                newUser = User.objects.create(username=username, email=email, password=password)
                success_msg = "Thank You for registering!!"
                return render(request, 'social/login.html', {'success_msg':success_msg})
        else:
            error_msg = "Enter all the details correctly"
            return render(request, 'social/register.html', {'error_msg': error_msg, 'form': form})
    else:
        form = RegisterForm()
        return render(request, 'social/register.html', {'form': form})

def login(request):
    if 'is_logged_in' not in request.session or request.session['is_logged_in'] == False:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                keep_logged_in = form.cleaned_data['keep_logged_in']
                if User.objects.filter(username=username).exists():
                    if User.objects.get(username=username).password == password:
                        userid = User.objects.get(username=username).id
                        request.session['user_id'] = userid
                        request.session['is_logged_in'] = True
                        if keep_logged_in == False:
                            request.session.set_expiry(0)
                        else:
                            request.session.set_expiry(130000000)
                        return render(request, 'trainapp/index.html')
                    else:
                        error_msg = "Incorrect credentials"
                        return render(request, 'social/login.html', {'error_msg': error_msg, 'form': form})
                else:
                    error_msg = "Username does not exists!"
                    return render(request, 'social/login.html', {'error_msg': error_msg, 'form': form})
            else:
                error_msg = "Error vaild form!"
                return render(request, 'social/login.html', {'error_msg':error_msg ,'form': form})
        else:
            form = LoginForm()
            return render(request, 'social/login.html', {'form': form})
    else:
        if request.session['is_logged_in']==True:
            return HttpResponseRedirect(reverse('social:index'))
        else:
            form = LoginForm()
            return render(request, 'social/login.html', {'form':form})

def logout(request):
    request.session['is_logged_in'] = False
    return HttpResponseRedirect(reverse('social:login'))

def live_status(request):
    if request.method == 'POST':
        form = trainStatus(request.POST)
        if form.is_valid():
            train_number = form.cleaned_data['train_number']
            date = form.cleaned_data['date']
            apikey = "6a721e3ch2"
            jsonList = []
            req = requests.get("http://api.railwayapi.com/v2/live/train/%s/date/%s/apikey/%s/"%(train_number, date, apikey))
            if req:
                jsonList.append(json.loads(req.content))
                traindata = {}
                trainroute ={}
                for data in jsonList:
                    traindata['train_number'] = data['train_number']
                    traindata['name'] = data['train']['name']
                    traindata['debit'] = data['debit']
                    trainroute['route'] = data['route']
                return render(request, 'trainapp/live_status.html', { 'trainData':traindata, 'trainRoute':trainroute })
            else:
                error_msg = "Train Number does not exists"
                return render(request, 'trainapp/live_status.html', {'error_msg': error_msg})
        else:
            error_msg = "Form validation error!!"
            return render(request, 'trainapp/live_status.html', {'error_msg': error_msg})
    else:
        form = trainStatus()
        return render(request, 'trainapp/live_status.html', {'form': form})

def pnr_status(request):
    if request.method == 'POST':
        form = pnrStatus(request.POST)
        if form.is_valid():
            pnr_number = form.cleaned_data['pnr_number']
            apikey = "6a721e3ch2"
            jsonList = []
            req = requests.get("http://api.railwayapi.com/v2/pnr-status/pnr/%s/apikey/%s/"%(pnr_number, apikey))
            if req:
                jsonList.append(json.loads(req.content))
                return render(request, 'trainapp/pnr_status.html', { 'pnrData':jsonList })
            else:
                error_msg = "Train Number does not exists"
                return render(request, 'trainapp/pnr_status.html', {'error_msg':error_msg})
        else:
            error_msg = "Form validation error!!"
            return render(request, 'trainapp/pnr_status.html', {'error_msg': error_msg})
    else:
        form = pnrStatus()
        return render(request, 'trainapp/pnr_status.html', {'form': form})

def train_route(request):
    if request.method == 'POST':
        form = trainStatus(request.POST)
        if form.is_valid():
            train_number = form.cleaned_data['train_number']
            d = datetime.date.today()
            date = str(d.strftime('%d-%m-%Y'))
            apikey = "6a721e3ch2"
            jsonList = []
            req = requests.get("http://api.railwayapi.com/v2/route/train/%s/apikey/%s/"%(train_number, apikey))
            if req:
                jsonList.append(json.loads(req.content))
                traindata = {}
                trainroute = {}
                for data in jsonList:
                    traindata['train'] = data['train']
                    trainroute['route'] = data['route']
                return render(request, 'trainapp/train_route.html', {'trainRoute':trainroute, 'trainData':traindata})
            else:
                error_msg = "Train Number does not exists"
                return render(request, 'trainapp/train_route.html', {'error_msg':error_msg})
        else:
            error_msg = "Form validation error!!"
            return render(request, 'trainapp/train_route.html', {'error_msg': error_msg})
    else:
        form = trainStatus()
        return render(request, 'trainapp/train_route.html', {'form': form})

def train_auto(request):
    if request.method == 'POST':
        form = Info(request.POST)
        if form.is_valid():
            info = form.cleaned_data['info']
            apikey = "6a721e3ch2"

            jsonList = []
            req = requests.get("http://api.railwayapi.com/v2/suggest-train/train/%s/apikey/%s/"%(info, apikey))
            jsonList.append(json.loads(req.content))
            return render(request, 'trainapp/train_auto.html', {'train_info':jsonList})
        else:
            error_msg = "Form validation error!!"
            return render(request, 'trainapp/train_auto.html', {'error_msg': error_msg})
    else:
        form = Info()
        return render(request, 'trainapp/train_auto.html', {'form': form})

def station_auto(request):
    if request.method == 'POST':
        form = Info(request.POST)
        if form.is_valid():
            info = form.cleaned_data['info']
            apikey = "6a721e3ch2"

            jsonList = []
            req = requests.get("http://api.railwayapi.com/v2/suggest-station/name/%s/apikey/%s/" % (info, apikey))
            jsonList.append(json.loads(req.content))
            return render(request, 'trainapp/station_auto.html', {'station_info': jsonList})
        else:
            error_msg = "Form validation error!!"
            return render(request, 'trainapp/station_auto.html', {'error_msg': error_msg})
    else:
        form = Info()
        return render(request, 'trainapp/station_auto.html', {'form': form})


def seat_availability(request):
    if request.method == 'POST':
        form = seatAvailability(request.POST)
        if form.is_valid():
            train_number = form.cleaned_data['train_number']
            source_code = form.cleaned_data['source_code']
            dest_code = form.cleaned_data['dest_code']
            class_code = form.cleaned_data['class_code']
            quota_code = form.cleaned_data['quota_code']
            date = form.cleaned_data['date']
            apikey = "6a721e3ch2"
            jsonList = []
            req = requests.get("http://api.railwayapi.com/v2/check-seat/train/%s/source/%s/dest/%s/date/%s/class/%s/quota/%s/apikey/%s/"%(train_number, source_code, dest_code, date, class_code, quota_code, apikey))
            if req:
                jsonList.append(json.loads(req.content))
                seat_availability = {}

social/templates/trainapp/cancelled_train.html
{% extends "trainapp/base.html" %}
{% block content %}
<center>
    <h2>Indian Railways Live Station</h2><br>
<form method="post" action="{% url 'social:cancelled_train' %}">
    {% csrf_token %}
    <input type="text" name="date" style="width:50%; border-radius:5px;height:40px;" placeholder="   Date ( dd-mm-yyyy )"><br><br>
    <input type="submit" style="height:40px; width:125px; background-color:#cce6ff; border-radius:5px;" value="Cancelled Trains">
</form>
<br><br>
    {% if error_msg %}
    {% elif cancelled_train %}
    <div class="container">
            <div class="table-responsive">
                <table id="table" class="table-striped table-responsive" style="width:90%;">
                    <tr>
                        <th>Train No</th>
                        <th>Train Name</th>
                        <th>Train Type</th>
                        <th>Source</th>
                        <th>Start Time</th>
                        <th>Destination</th>
                    </tr>

                    {% for value_list  in cancelled_train %}
                        {% for value in value_list.trains %}
                        <tr>
                        <td>{{ value.number }}</td>
                        <td>{{ value.name }}</td>
                        <td>{{ value.type }}</td>
                        <td>{{ value.source.name }}</td>
                        <td>{{ value.start_time }}</td>
                        <td>{{ value.dest.name }}</td>
                        </tr>
                        {% endfor %}
                    {% endfor %}

                </table>
            </div>
        </div>
    {% endif %}
</center>

{% endblock %}

social/templates/trainapp/fare_enquiry.html
{% extends "trainapp/base.html" %}
{% block content %}
<center>
    <h2>Indian Railways Train Route</h2><br>
<form method="post" action="{% url 'social:fare_enquiry' %}">
    {% csrf_token %}
    <input type="text" name="train_number" style="width:50%; border-radius:5px;height:40px;" placeholder="   Train Number"><br><br>
    <input type="text" name="source_code" style="width:50%; border-radius:5px;height:40px;" placeholder="   Source Station"><br><br>
    <input type="text" name="dest_code" style="width:50%; border-radius:5px;height:40px;" placeholder="   Destination Station"><br><br>
    <input type="text" name="age" style="width:50%; border-radius:5px;height:40px;" placeholder="   Age"><br><br>
    <input type="text" name="date" style="width:50%; border-radius:5px;height:40px;" placeholder="   Date ( dd-mm-yyyy )"><br><br>
    <input type="text" name="quota_code" style="width:50%; border-radius:5px;height:40px;" placeholder="   Quota Code"><br><br>
    <input type="submit" style="height:40px; width:125px; background-color:#cce6ff; border-radius:5px;" value="Get Fare">
</form>
<br><br>
    {% if error_msg %}
    {% elif fare_data %}
    <div class="container">
            <div class="table-responsive">
                <table id="table" class="table-striped table-responsive" style="width:90%;">
                    <tr>
                        <th>Train No</th>
                        <th>Train Name</th>
                        <th>From Station</th>
                        <th>Destination</th>
                        <th>Quota</th>
                        {% for value_list  in fare_data %}
                            {% for value in value_list.fare %}
                                <th>{{ value.code }}</th>
                            {% endfor %}
                        {% endfor %}
                    </tr>

                    {% for value_list  in fare_data %}
                    <tr>
                        <td>{{ value_list.train.number }}</td>
                        <td>{{ value_list.train.name }}</td>
                        <td>{{ value_list.from_station.name }}</td>
                        <td>{{ value_list.to_station.name }}</td>
                        <td>{{ value_list.quota.code }}</td>
                        {% for value in value_list.fare %}
                            <td>{{ value.fare }}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    {% endif %}
</center>

{% endblock %}

social/templates/trainapp/live_station.html
{% extends "trainapp/base.html" %}
{% block content %}
<center>
    <h2>Indian Railways Live Station</h2><br>
<form method="post" action="{% url 'social:live_station' %}">
    {% csrf_token %}
    <input type="text" name="station_code" style="width:50%; border-radius:5px;height:40px;" placeholder="   Station Code"><br><br>
    <input type="text" name="hours" style="width:50%; border-radius:5px;height:40px;" placeholder="   Hours ( 2 or 4 )"><br><br>
    <input type="submit" style="height:40px; width:125px; background-color:#cce6ff; border-radius:5px;" value="Live Station">
</form>
<br><br>
    {% if error_msg %}
    {% elif live_station %}
    <div class="container">
            <div class="table-responsive">
                <table id="table" class="table-striped table-responsive" style="width:90%;">
                    <tr>
                        <th>Train No</th>
                        <th>Train Name</th>
                        <th>Sch Arr</th>
                        <th>Act Arr</th>
                        <th>Delay Arr</th>
                        <th>Sch Dep</th>
                        <th>Act Dep</th>
                        <th>Delay Dep</th>
                    </tr>

                    {% for value_list  in live_station %}
                        {% for value in value_list.train %}
                        <tr>
                        <td>{{ value.number }}</td>
                        <td>{{ value.name }}</td>
                        <td>{{ value.scharr }}</td>
                        <td>{{ value.actarr }}</td>
                        <td>{{ value.delayarr }}</td>
                        <td>{{ value.schdep }}</td>
                        <td>{{ value.actdep }}</td>
                        <td>{{ value.delaydep }}</td>
                        </tr>
                        {% endfor %}
                    {% endfor %}

                </table>
            </div>
        </div>
    {% endif %}
</center>

{% endblock %}

social/templates/trainapp/live_status.html
{% extends "trainapp/base.html" %}
{% block content %}
<center>
    <h2>Indian Railways Live Train Running Status</h2><br>
<form method="post" action="{% url 'social:live_status' %}">
    {% csrf_token %}
    <input type="text" name="train_number" style="width:50%; border-radius:5px;height:40px;" placeholder="   Train Number"><br><br>
    <input type="text" name="date" style="width:50%; border-radius:5px;height:40px;" placeholder="   Date ( dd-mm-yyyy )"><br><br>
    <input type="submit" style="height:40px; width:125px; background-color:#cce6ff; border-radius:5px;" value="Get Live Status">
</form>
<br><br>
    {% if error_msg %}
    {% elif trainRoute %}
    <div class="container">
            <div class="table-responsive">
                <table id="table" class="table-striped table-responsive" style="width:90%;">
                    <tr>
                        <th>No</th>
                        <th>Station Name</th>
                        <th>Sch. Arrival</th>
                        <th>Sch. Departure</th>
                        <th>Arrived</th>
                        <th>Departed</th>
                        <th>Actual Arr(Delay in min)</th>
                        <th>Actual Dep(Delay in min)</th>
                    </tr>

                    {% for key, value_list  in trainRoute.items %}
                        {% for value in value_list %}
                        <tr>
                            <td>{{ value.no }}</td>
                            <td>{{ value.station.name }}</td>
                            <td>{{ value.scharr }}</td>
                            <td>{{ value.schdep }}</td>
                            <td>
                                {% if value.has_arrived|yesno:"Yes,No,Maybe" == "Yes" %}
                                    <span style="color:green">Yes</span>
                                {% endif %}
                                {% if value.has_arrived|yesno:"Yes,No,Maybe" == "No" %}
                                    <span style="color:red">No</span>
                                {% endif %}
                                {% if value.has_arrived|yesno:"Yes,No,Maybe" == "Maybe" %}
                                    <span style="color:blue">Maybe</span>
                                {% endif %}
                            </td>
                            <td>
                                {% if value.has_departed|yesno:"Yes,No,Maybe" == "Yes" %}
                                    <span style="color:green">Yes</span>
                                {% endif %}
                                {% if value.has_departed|yesno:"Yes,No,Maybe" == "No" %}
                                    <span style="color:red">No</span>
                                {% endif %}
                                {% if value.has_departed|yesno:"Yes,No,Maybe" == "Maybe" %}
                                    <span style="color:blue">Maybe</span>
                                {% endif %}
                            </td>
                            <td>{{ value.actarr}} ( {{value.latemin}} )</td>
                            <td>{{ value.actdep}} ( {{value.latemin}} )</td>
                        </tr>
                        {% endfor %}
                    {% endfor %}

                </table>
            </div>
        </div>
    {% endif %}
</center>

{% endblock %}

social/templates/trainapp/pnr_status.html
{% extends "trainapp/base.html" %}
{% block content %}
<center>
    <h2>Indian Railways PNR Status</h2><br>
<form method="post" action="{% url 'social:pnr_status' %}">
    {% csrf_token %}
    <input type="text" name="pnr_number" style="width:75%; border-radius:5px;height:40px;" placeholder="   PNR Number"><br><br>
    <input type="submit" style="height:40px; width:125px; background-color:#cce6ff; border-radius:5px;" value="Get PNR Status">
</form>
<br><br>
    {% if error_msg %}
    {% elif pnrData %}
    <div class="container">
            <div class="table-responsive">
                <table id="table" class="table-striped table-responsive" style="width:90%;">
                    <tr>
                        <th>Train No</th>
                        <th>Train Name</th>
                        <th>Boarding Date</th>
                        <th>From</th>
                        <th>Reserved Upto</th>
                        <th>Boarding Point</th>
                        <th>Class</th>
                    </tr>

                    {% for value in pnrData %}
                        <tr>
                            <td>{{ value.train.number }}</td>
                            <td>{{ value.train.name }}</td>
                            <td>{{ value.doj }}</td>
                            <td>{{ value.from_station.name }}</td>
                            <td>{{ value.to_station.name }}</td>
                            <td>{{ value.boarding_point.code}}</td>
                            <td>{{ value.journey_class.name}}</td>
                        </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    {% endif %}
</center>

{% endblock %}

social/templates/trainapp/rescheduled.html
{% extends "trainapp/base.html" %}
{% block content %}
<center>
    <h2>Indian Railways Rescheduled Trains</h2><br>
<form method="post" action="{% url 'social:rescheduled_train' %}">
    {% csrf_token %}
    <input type="text" name="date" style="width:50%; border-radius:5px;height:40px;" placeholder="   Date ( dd-mm-yyyy )"><br><br>
    <input type="submit" style="height:40px; width:175px; background-color:#cce6ff; border-radius:5px;" value="Rescheduled Train">
</form>
<br><br>
    {% if error_msg %}
    {% elif rescheduled %}
    <div class="container">
            <div class="table-responsive">
                <table id="table" class="table-striped table-responsive" style="width:90%;">
                    <tr>
                        <th>Train No</th>
                        <th>Train Name</th>
                        <th>Source</th>
                        <th>Destination</th>
                        <th>Rescheduled Time</th>
                        <th>Rescheduled Date</th>
                        <th>Time Diff.</th>
                    </tr>

                    {% for value_list  in rescheduled %}
                        {% for value in value_list.trains %}
                        <tr>
                        <td>{{ value.number }}</td>
                        <td>{{ value.name }}</td>
                        <td>{{ value.from_station.name }}</td>
                        <td>{{ value.to_station.name }}</td>
                        <td>{{ value.rescheduled_time }}</td>
                        <td>{{ value.rescheduled_date }}</td>
                        <td>{{ value.time_diff }}</td>
                        </tr>
                        {% endfor %}
                    {% endfor %}

                </table>
            </div>
        </div>
    {% endif %}
</center>

{% endblock %}

social/templates/trainapp/seat_availability.html
{% extends "trainapp/base.html" %}
{% block content %}
<center>
    <h2>Indian Railways Seat Availability</h2><br>
<form method="post" action="{% url 'social:seat_availability' %}">
    {% csrf_token %}
    <input type="text" name="train_number" style="width:50%; border-radius:5px;height:40px;" placeholder="   Train Number"><br><br>
    <input type="text" name="source_code" style="width:50%; border-radius:5px;height:40px;" placeholder="   Source Station"><br><br>
    <input type="text" name="dest_code" style="width:50%; border-radius:5px;height:40px;" placeholder="   Destination Station"><br><br>
    <input type="text" name="date" style="width:50%; border-radius:5px;height:40px;" placeholder="   Date ( dd-mm-yyyy )"><br><br>
    <input type="text" name="quota_code" style="width:50%; border-radius:5px;height:40px;" placeholder="   Quota Code"><br><br>
    <input type="text" name="class_code" style="width:50%; border-radius:5px;height:40px;" placeholder="   Class Code"><br><br>
    <input type="submit" style="height:40px; width:125px; background-color:#cce6ff; border-radius:5px;" value="Seat Availability">
</form>
<br><br>
    {% if error_msg %}
    {% elif train_data %}
    <div class="container">
            <div class="table-responsive">
                <table id="table" class="table-striped table-responsive" style="width:90%;">
                    <tr>
                        <th>Train No</th>
                        <th>Train Name</th>
                        <th>Date</th>
                        <th>Source Station</th>
                        <th>Destination Station</th>
                        <th>Quota Code</th>
                        <th>Class Code</th>
                    </tr>

                    <tr>
                        <td>{{ train_data.number }}</td>
                        <td>{{ train_data.name }}</td>
                        <td>{{ date }}</td>
                        <td>{{ from_station }}</td>
                        <td>{{ to_station }}</td>
                        <td>{{ quota }}</td>
                        <td>{{ class_code }}</td>
                    </tr>

                </table>
            </div>
        </div>

    <br><br><br>
        <div class="container">
            <div class="table-responsive">
                <table id="table" class="table-striped table-responsive" style="width:50%;">
                    <tr>
                        <th style="width: 25%;">Date</th>
                        <th style="width: 25%;">Class - {{class_code}}</th>
                    </tr>

                    {% for key, value_list  in seat_availability.items %}
                        {% for value in value_list %}
                        <tr>
                            <td>{{ value.date}}</td>
                            <td>{{ value.status}}</td>
                        </tr>
                        {% endfor %}
                    {% endfor %}

                </table>
            </div>
        </div>
    {% endif %}
</center>

{% endblock %}

social/templates/trainapp/station_auto.html
{% extends "trainapp/base.html" %}
{% block content %}
<center>
    <h2>Indian Railways Station</h2><br>
<form method="post" action="{% url 'social:station_auto' %}">
    {% csrf_token %}
    <input type="text" name="info" style="width:75%; border-radius:5px;height:40px;" placeholder="   Station Name <Partial/Full>"><br><br>
    <input type="submit" style="height:40px; width:150px; background-color:#cce6ff; border-radius:5px;" value="Get Station Info">
</form>
    <br><br>
{% if error_msg %}

{% elif station_info %}
    <div class="container">
            <div class="table-responsive">
                <table id="table" class="table-striped table-responsive" style="width:25%;">
                    <tr>
                        <th style="padding-left: 25px;">Station Code</th>
                        <th>Station Name</th>
                    </tr>

                    {% for value_list  in station_info %}
                        {% for value in value_list.stations %}
                        <tr>
                            <td style="padding-left: 25px;">{{ value.code }}</td>
                            <td>{{ value.name }}</td>
                        </tr>
                        {% endfor %}
                    {% endfor %}

                </table>
            </div>
        </div>
    <br/><br/>
    {% endif %}
</center>
{% endblock %}
